### ISSUE TITLE
Plotly Component Failing on Numpy Values

### ISSUE THREAD

**Issue by Red-Giuliano** [Zero-True/zero-true#143]
Reproducible example:

import pandas as pd
import zero_true as zt 
# Generating a mock dataframe for the plot
# Assuming a show with 5 seasons and 10 episodes per season
seasons = 5
episodes_per_season = 10
total_episodes = seasons * episodes_per_season

# Creating season and episode data
season_data = [season for season in range(1, seasons + 1) for _ in range(episodes_per_season)]
episode_data = [episode for _ in range(seasons) for episode in range(1, episodes_per_season + 1)]

# Creating mock ratings data
import random
random.seed(0) # for reproducibility
ratings_data = [round(random.uniform(6.0, 10.0), 1) for _ in range(total_episodes)]

# Creating the dataframe
mock_ratings_df = pd.DataFrame({
    'season': season_data,
    'episode': episode_data,
    'rating': ratings_data
})

# Adding 'Season and Episode' column
mock_ratings_df['Season and Episode'] = 'S' + mock_ratings_df['season'].astype(str) + ' Ep' + mock_ratings_df['episode'].astype(str)
fig = go.Figure(go.Scatter(x = ratings_df.index,y=ratings_df.rating))
fig.update_layout(xaxis = dict(tickmode='array',tickvals = ratings_df.index,ticktext=ratings_df['Season and Episode'].tolist()))
fig.update_traces(mode='markers+lines')
plt = zt.PlotlyComponent.from_figure(figure=fig, id = 'plot')

Backend will display the following error:

Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\Users\rg\anaconda3\envs\pbd-comp\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\rg\anaconda3\envs\pbd-comp\lib\site-packages\zt_backend\router.py", line 54, in __run
    self.__run_backup()
  File "C:\Users\rg\anaconda3\envs\pbd-comp\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rg\anaconda3\envs\pbd-comp\lib\site-packages\zt_backend\runner\execute_code.py", line 101, in execute_request
    execution_state.message_queue.put_nowait(cell_response.model_dump_json())
  File "C:\Users\rg\anaconda3\envs\pbd-comp\lib\site-packages\pydantic\main.py", line 352, in model_dump_json
    return self.__pydantic_serializer__.to_json(
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationError: Unable to serialize unknown type: <class 'numpy.ndarray'>

Unfortunately there is no error displayed on the frontend, the code run just seems to hang.

**Comment by Carson-Shaar** [comment]
Fixed
