### ISSUE TITLE
TOML Won't load a list or dict with mixed types

### ISSUE THREAD

**Issue by Red-Giuliano** [Zero-True/zero-true#37]
See the following two issues:

https://github.com/uiri/toml/issues/270

https://github.com/python-poetry/poetry/issues/7094

From the second issue it seems like we want to switch to tomlib or tomli:

https://github.com/hukkin/tomli

https://docs.python.org/3/library/tomllib.html

**Comment by Carson-Shaar** [comment]
Resolved
