### ISSUE TITLE
Button Isn't Working

### ISSUE THREAD

**Issue by Red-Giuliano** [Zero-True/zero-true#60]
**Button isn't working as expected**
Button sends run code command but does not update value to True. 

**To Reproduce**
1. zero-true notebook
2. Type 

import zero-true as zt

btn = zt.Button(id='btn')

btn.value

4. Notice how on click code is run but value is always false.

**Expected behavior**

Value should be true on click

**Comment by Carson-Shaar** [comment]
Resolved
